# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Team.create!(acronym: 'ALG', name_en: 'Algeria',                name_pt: 'Algéria')
Team.create!(acronym: 'ARG', name_en: 'Argentina',              name_pt: 'Argentina')
Team.create!(acronym: 'AUS', name_en: 'Australia',              name_pt: 'Austrália')
Team.create!(acronym: 'BEL', name_en: 'Belgium',                name_pt: 'Bélgica')
Team.create!(acronym: 'BIH', name_en: 'Bosnia and Herzegovina', name_pt: 'Bósnia e Herzegovina')
Team.create!(acronym: 'BRA', name_en: 'Brazil',                 name_pt: 'Brasil')
Team.create!(acronym: 'CHI', name_en: 'Chile',                  name_pt: 'Chile')
Team.create!(acronym: 'CIV', name_en: "Côte d'Ivoire",          name_pt: 'Costa do Marfim')
Team.create!(acronym: 'CMR', name_en: 'Cameroon',               name_pt: 'Camarões')
Team.create!(acronym: 'COL', name_en: 'Colombia',               name_pt: 'Colômbia')
Team.create!(acronym: 'CRC', name_en: 'Costa Rica',             name_pt: 'Costa Rica')
Team.create!(acronym: 'CRO', name_en: 'Croatia',                name_pt: 'Croácia')
Team.create!(acronym: 'ECU', name_en: 'Ecuador',                name_pt: 'Equador')
Team.create!(acronym: 'ENG', name_en: 'England',                name_pt: 'Inglaterra')
Team.create!(acronym: 'ESP', name_en: 'Spain',                  name_pt: 'Espanha')
Team.create!(acronym: 'FRA', name_en: 'France',                 name_pt: 'França')
Team.create!(acronym: 'GER', name_en: 'Germany',                name_pt: 'Alemanha')
Team.create!(acronym: 'GHA', name_en: 'Ghana',                  name_pt: 'Gana')
Team.create!(acronym: 'GRE', name_en: 'Greece',                 name_pt: 'Grécia')
Team.create!(acronym: 'HON', name_en: 'Honduras',               name_pt: 'Honduras')
Team.create!(acronym: 'IRN', name_en: 'Iran',                   name_pt: 'Irã')
Team.create!(acronym: 'ITA', name_en: 'Italy',                  name_pt: 'Itália')
Team.create!(acronym: 'JPN', name_en: 'Japan',                  name_pt: 'Japão')
Team.create!(acronym: 'KOR', name_en: 'Korea Republic',         name_pt: 'Coreia do Sul')
Team.create!(acronym: 'MEX', name_en: 'Mexico',                 name_pt: 'México')
Team.create!(acronym: 'NED', name_en: 'Netherlands',            name_pt: 'Holanda')
Team.create!(acronym: 'NGA', name_en: 'Nigeria',                name_pt: 'Nigéria')
Team.create!(acronym: 'POR', name_en: 'Portugal',               name_pt: 'Portugal')
Team.create!(acronym: 'RUS', name_en: 'Russia',                 name_pt: 'Rússia')
Team.create!(acronym: 'SUI', name_en: 'Switzerland',            name_pt: 'Suíça')
Team.create!(acronym: 'URU', name_en: 'Uruguay',                name_pt: 'Uruguai')
Team.create!(acronym: 'USA', name_en: 'USA',                    name_pt: 'EUA')
